name: cnn-decoder
sensors:
  vision:
    - ${dataset.num_colours}
    - ${dataset.vision_height}
    - ${dataset.vision_width}
connections:
  - ["vision", "cnn_encoder"]
  - ["cnn_encoder", "fc_feedforward"]
  - ["fc_feedforward", "classifier"]
  - ["cnn_encoder", "decoder"]
circuits:
  cnn_encoder:
    _target_: retinal_rl.models.circuits.convolutional.ConvolutionalEncoder
    num_layers: 4
    num_channels: [16,32,64,64]
    kernel_size: ${kernel_size}
    stride:  ${stride}
    act_name: ${activation}
    loss_weights:
      classification: 0.1
      reconstruction: 0.9
    reg_weights:
      l1_weight: 0.0001
      l2_weight: 0.0001
    optimizer:
      _target_: torch.optim.Adam
      lr: 0.0003
  fc_feedforward:
    _target_: retinal_rl.models.circuits.fully_connected.FullyConnectedEncoder
    output_shape:
      - ${latent_dimension}
    hidden_units: []
    act_name: ${activation}
    optimizer:
      _target_: torch.optim.Adam
      lr: 0.0003
    loss_weights:
      classification: 0.1
      reconstruction: 0.9
    reg_weights:
      l1_weight: 0.0001
      l2_weight: 0.0001
  decoder:
    _target_: retinal_rl.models.circuits.convolutional.ConvolutionalDecoder
    num_layers: 4
    num_channels: [64,32,16,3]
    kernel_size: ${kernel_size}
    stride:  ${stride}
    act_name: ${activation}
    optimizer:
      _target_: torch.optim.Adam
      lr: 0.0003
    loss_weights:
      classification: 0.1
      reconstruction: 0.9
    reg_weights:
      l1_weight: 0.0001
      l2_weight: 0.0001
  classifier:
    _target_: retinal_rl.models.circuits.task_head.linear_classifier.LinearClassifier
    num_classes: ${dataset.num_classes}
    optimizer:
      _target_: torch.optim.Adam
      lr: 0.0003
    loss_weights:
      classification: 0.1
      reconstruction: 0.9
    reg_weights:
      l1_weight: 0.0001
      l2_weight: 0.0001
