defaults:
  - _self_
  - command: scan
  - dataset: ??

hydra:
  output_subdir: config
  run:
    dir: experiments/${experiment}
  job:
    chdir: True
  searchpath:
    - file://config/user

system:
  device: cpu
  experiment_path: ${hydra:run.dir}
  data_path: data
  checkpoint_path: ${system.data_path}/checkpoints
  max_checkpoints: 5
  plot_path: ${system.data_path}/plots
  checkpoint_plot_path: ${system.data_path}/plots/checkpoint
