defaults:
  - _self_
  - dataset: ??
  - sweep: ??
  - brain: ??
  - override hydra/job_logging: custom

command: scan
run_name: 'run_${now:%Y-%m-%d-%H-%M-%S}'

training:
  recon_weight: 0.9
  learning_rate: 0.0003
  num_epochs: 100
  checkpoint_step: 5


hydra:
  output_subdir: config
  run:
    dir: experiments/${experiment}/single-run/${run_name}
  job:
    chdir: True
    config:
      override_dirname:
        exclude_keys:
          - experiment
          - command
  searchpath:
    - file://config/user
  sweep:
    dir: experiments/${experiment}/sweep/${oc.env:WANDB_SWEEP_ID,local}
    subdir: ${run_name}
system:
  device: cuda
  run_dir: ${hydra:runtime.output_dir}
  data_dir: data
  checkpoint_dir: ${system.data_dir}/checkpoints
  max_checkpoints: 5
  plot_dir: ${system.data_dir}/plots
  checkpoint_plot_dir: ${system.plot_dir}/checkpoints

logging:
  use_wandb: True

sweep:
  command:
    - \${env}
    - python
    - \${program}
    - -m
    - command=train
    - +experiment=${experiment}
    - \${args_no_hyphens}
