defaults:
  - _self_
  - command: scan
  - dataset: ??
  - brain: ??
  - override hydra/job_logging: custom

run_name: 'run_${now:%Y-%m-%d-%H-%M-%S}'

hydra:
  output_subdir: config
  run:
    dir: experiments/${experiment}/${run_name}
  job:
    chdir: True
    config:
      override_dirname:
        exclude_keys:
          - experiment
          - command
  searchpath:
    - file://config/user
  sweep:
<<<<<<< HEAD
    dir: experiments/${experiment}/sweep/${oc.env:WANDB_SWEEP_ID,local}
    subdir: ${run_id}
=======
    dir: experiments/${experiment}/sweep/${get_sweep_dir:experiments/sweep}
    subdir: ${run_name}
>>>>>>> 660d8d5 (Leaving id up to wandb to decide. Just going to set run names...)

system:
  device: cuda
  experiment_path: ${hydra:runtime.output_dir}
  data_path: data
  checkpoint_path: ${system.data_path}/checkpoints
  max_checkpoints: 5
  plot_path: ${system.data_path}/plots
  checkpoint_plot_path: ${system.data_path}/plots/checkpoint

logging:
  use_wandb: true

sweep:
  command:
    - \${env}
    - python
    - \${program}
    - -m
    - command=train
    - +experiment=${experiment}
    - \${args_no_hyphens}
