absl-py==1.2.0
cachetools==5.2.0
certifi==2022.9.24
charset-normalizer==2.1.1
click==8.1.3
cloudpickle==2.2.0
colorlog==6.7.0
contourpy==1.0.5
cycler==0.11.0
Cython==0.29.32
docker-pycreds==0.4.0
faster-fifo==1.4.2
filelock==3.8.0
fonttools==4.37.3
gitdb==4.0.9
GitPython==3.1.27
google-auth==2.11.1
google-auth-oauthlib==0.4.6
greenlet==1.1.2
grpcio==1.49.1
gym==0.25.2
gym-notices==0.0.8
idna==3.4
imageio==2.22.0
joblib==1.1.0
kiwisolver==1.4.4
Markdown==3.4.1
MarkupSafe==2.1.1
matplotlib==3.6.0
msgpack==1.0.3
nodeenv==1.7.0
numpy==1.23.3
oauthlib==3.2.1
opencv-python==4.6.0.66
openTSNE==0.6.2
packaging==21.3
pathtools==0.1.2
Pillow==9.2.0
promise==2.3
protobuf==3.19.5
psutil==5.9.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pygifsicle==1.0.6
pyglet==1.5.27
pynvim==0.4.2
pyparsing==3.0.9
pyright==1.1.272
python-dateutil==2.8.2
PyYAML==6.0
requests==2.28.1
requests-oauthlib==1.3.1
rsa==4.9
sample-factory==1.123.0
scikit-learn==1.0.2
scipy==1.9.1
sentry-sdk==1.9.8
setproctitle==1.3.2
shortuuid==1.0.9
six==1.16.0
smmap==5.0.0
support-developer==1.0.4
tensorboard==2.10.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorboardX==2.5.1
threadpoolctl==3.1.0
torch==1.12.1+cu116
torchaudio==0.12.1+cu116
torchvision==0.13.1+cu116
typing_extensions==4.3.0
urllib3==1.26.12
vizdoom==1.1.13
wandb==0.13.3
Werkzeug==2.2.2
