description: Sweeping performance of models on gathering tasks of increasing visual
  complexity.
method: grid
name: production-alpha-gathering-feedforward
parameters:
  activation:
    value: elu
  base_channels:
    value: 16
  experiment:
    value: repeat-{repeat}_env-{env}_input_satiety-{input_satiety}
  normalize_returns:
    value: false
  num_envs_per_worker:
    value: 8
  num_workers:
    value: 16
  online_analysis:
    value: false
  optimizer:
    value: adam
  recurrence:
    value: 32
  res_h:
    value: 120
  res_w:
    value: 160
  rnn_size:
    value: 32
  rollout:
    value: 32
  train_dir:
    value: train_dir/production-alpha/gathering-feedforward
  train_for_env_steps:
    value: 10000000000
  use_rnn:
    value: false
  vision_model:
    value: retinal
  wandb_job_type:
    value: gathering-feedforward
  with_vtrace:
    value: true
