reconstruction:
  optimizer:
    _target_: torch.optim.Adam
    lr: 0.0003
  min_epoch: 0
  max_epoch: 10
  objectives:
    - _target_: retinal_rl.models.objective.ReconstructionObjective
      weight: 1
    # - _target_: retinal_rl.models.objective.L1Sparsity
    #   weight: 0.01
    #   targets:
    #     - cnn_encoder1
    # - _target_: retinal_rl.models.objective.L2WeightRegularizer
    #   weight: 0.01
  target_circuits:
    - cnn_encoder1
    - decoder
classification:
  optimizer:
    _target_: torch.optim.Adam
    lr: 0.0003
  min_epoch: 11
  objectives:
    - _target_: retinal_rl.classification.objective.ClassificationObjective
      weight: 0.1
    - _target_: retinal_rl.classification.objective.PercentCorrect
      weight: 0
  target_circuits:
    - cnn_encoder2
    - fc_feedforward
    - classifier
