name: cifar10
num_classes: 10
num_colours: 3
vision_width: 160
vision_height: 160
visual_field: 
  - ${dataset.vision_height}
  - ${dataset.vision_width}
image_rescale_range: [1,5]
sample_size_multiplier: 5
