description: Trains neural networks to classify scaled and shifted CIFAR10 images.
program: main.py
method: grid
project: retinal-rl

parameters:
  latent_dimension:
    values: [32,64,128]
  recon_weight:
    values: [0,0.25,0.5,0.75,1]
  kernel_size:
    values: ['[4,2,2,2]','[6,4,4,2]','[8,6,4,4]']

command:
  - ${env}
  - python
  - ${program}
  - +experiment=cifar10-classification
  - ${args_no_hyphens}
