# wandb sweep
description: Actually trying to find a good balance between recon and classification.
program: main.py
method: grid
project: retinal-rl

parameters:
  dataset.image_rescale_range:
    value: '[1,5]'
  kernel_size:
    value: '[8,6,4,2]'
  training.recon_weight:
    values: [0.9,0.95,0.99,0.995,0.999,0.9995,0.9999,0.99995]
