# wandb sweep
description: Comparing autoencoders where the decoding happens before or after the FC layer.
program: main.py
method: grid
project: retinal-rl

parameters:
  dataset.image_rescale_range:
    values: ['[1,1]', '[2,2]', '[3,3]', '[4,4]']
  kernel_size:
    values: ['[6,4,4,2]','[10,8,6,4]','[14,10,8,6]']
  training.recon_weight:
    values: [0.95,0,1]
