# wandb sweep
description: Evaluating what very variable image size does to RFs.
program: main.py
method: grid
project: retinal-rl

parameters:
  dataset.image_rescale_range:
    value: '[1,5]'
  kernel_size:
    values: ['[6,4,4,2]','[10,8,6,4]','[14,10,8,6]']
  training.recon_weight:
    values: [0.95,0,1]
