# @package _global_
defaults:
  - /brain: retinal
  - override /dataset: cifar10
  - _self_

rl_defaults:
  # This block shouldn't be messed with without extensive testing
  ppo_clip_value: 0.2
  obs_subtract_mean: 0.0
  obs_scale: 255.0
  env_frameskip: 4
  # Environment defaults we've settled on
  res_h: 120
  res_w: 160
  decorrelate_envs_on_one_worker: False
  wide_aspect_ratio: False
  # Wandb stuff
  with_wandb: "True"
  wandb_project: "retinal-rl"
  wandb_group: "free-range"
  wandb_job_type: "test"
  # System specific but we'll still set these defaults
  train_for_env_steps: int(1e10)
  batch_size: 2048
  num_workers: 20
  num_envs_per_worker: 8
  # All of these have been through some testing and work as good defaults
  exploration_loss: "symmetric_kl"
  exploration_loss_coeff: 0.001
  with_vtrace: True
  normalize_returns: False
  normalize_input: True
  recurrence: 32
  rollout: 32
  use_rnn: False
  rnn_size: 32
  # Evaluation-mode stuff
  eval_env_frameskip: 1  # this is for smoother rendering during evaluation
  fps: 35
  max_num_frames: 1000
  max_num_episodes: 100

retinal_env:
  # base_channels: 16 # These should be defined in the brain
  # retinal_bottleneck: None
  # retinal_stride: 1
  # vision_model: "retinal"
  # activation: "elu"
  input_satiety: False
  repeat: 1
  analysis_freq: 19e8
  online_analysis: False
  dry_run: False

retinal_env_eval:
  analysis_name: None
  receptive_fields: False
  simulate: False
  plot: False
  animate: False
  save_frames: False
  frame_step: 0
  sta_repeats: 200
  viewport_video: False
  append_sim: False