defaults:
  - _self_
  - circuits:
    - prototypical_encoder
    - prototypical_decoder
    - linear_classifier

name: brain
sensors:
  image: [3, 32, 32]
connections:
  - ["image", "prototypical_encoder"]
  - ["prototypical_encoder", "linear_classifier"]
  - ["prototypical_encoder", "prototypical_decoder"]
