# Configuration for the CIFAR10 dataset in classification experiments.

name: cifar10  # Name of the dataset

imageset:
  _target_: retinal_rl.dataset.Imageset
  source_transforms:
    - _target_: retinal_rl.datasets.transforms.ScaleShiftTransform
      vision_width: 160
      vision_height: 160
      image_rescale_range: [1, 5]
  noise_transforms:
    - _target_: retinal_rl.datasets.transforms.ShotNoiseTransform
      lambda_range: [0.5, 1.5]
    - _target_: retinal_rl.datasets.transforms.ContrastTransform
      contrast_range: [0.01, 1.2]
  apply_normalization: true
  fixed_transformation: false
  multiplier: 1
