defaults:
  - command: single_run
  - dataset: cifar10
  - _self_

training:
  num_folds: 5
  num_epochs: 10
  recon_weight: 0.5

sweep:
  latent_size: 4

brain:
  _target_: retinal_rl.models.brain.Brain
  name: brain
  sensors:
    vision: ${dataset.image_size}
  connections:
    - ["vision", "prototypical_encoder"]
    - ["prototypical_encoder", "linear_classifier"]
    - ["prototypical_encoder", "prototypical_decoder"]
  circuits:
    prototypical_encoder:
        _target_: retinal_rl.models.vision.prototypical.PrototypicalEncoder
        latent_size: ${sweep.latent_size}
        input_shape: ${dataset.image_size}
        act_name: "relu"
    prototypical_decoder:
        _target_: retinal_rl.models.vision.prototypical.PrototypicalDecoder
        latent_size: ${sweep.latent_size}
        input_shape: ${dataset.image_size}
        act_name: "relu"
    linear_classifier:
        _target_: retinal_rl.models.cognition.linear_classifier.LinearClassifier
        inp_size: ${sweep.latent_size}
        out_size: 10
        act_name: "elu"

hydra:
  output_subdir: config
  run:
    dir: experiment/${experiment}/${command}
  job:
    chdir: True

system:
  device: cpu
