defaults:
  - _self_
  - override hydra/job_logging: custom

command: scan
run_name: 'run_${now:%Y-%m-%d-%H-%M-%S}'

hydra:
  output_subdir: config
  run:
    dir: experiments/${experiment.name}/single-run/${run_name}
  job:
    chdir: True
    config:
      override_dirname:
        exclude_keys:
          - experiment
          - command
  sweep:
    dir: experiments/${experiment.name}/sweep/${oc.env:WANDB_SWEEP_ID,local}
    subdir: ${run_name}
system:
  device: cuda
  run_dir: ${hydra:runtime.output_dir}
  data_dir: data
  checkpoint_dir: ${system.data_dir}/checkpoints
  max_checkpoints: 5
  plot_dir: ${system.data_dir}/plots
  checkpoint_plot_dir: ${system.plot_dir}/checkpoints
  wandb_preempt: False

use_wandb: True

sweep:
  experiment:
    command:
      - \${env}
      - python
      - \${program}
      - -m
      - command=train
      - +experiment=${experiment}
      - \${args_no_hyphens}
