defaults:
  - _self_
  - command: scan
  - dataset: ??

hydra:
  output_subdir: config
  run:
    dir: experiment/${experiment}/${command.run_mode}
  job:
    chdir: True
  searchpath:
    - file://.

system:
  device: cpu
