optimizer: # torch.optim Class and parameters
  _target_: torch.optim.Adam
  lr: 0.0003

losses:
  - _target_: retinal_rl.classification.loss.PercentCorrect
  - _target_: retinal_rl.classification.loss.ClassificationLoss
    target_circuits: # Circuit parameters to optimize with this optimizer.  We train the retina and the decoder exclusively to maximize reconstruction
      - retina
      - thalamus
      - visual_cortex
      - inferotemporal
      - prefrontal
      - classifier
    weights:
      - ${eval:'1-${recon_weight_retina}'}
      - ${eval:'1-${recon_weight_thalamus}'}
      - ${eval:'1-${recon_weight_cortex}'}
      - 1
      - 1
      - 1
  - _target_: retinal_rl.models.loss.ReconstructionLoss
    min_epoch: 0 # Epoch to start optimizer
    max_epoch: 100 # Epoch to stop optimizer
    target_circuits: # Circuit parameters to optimize with this optimizer.  We train the retina and the decoder exclusively to maximize reconstruction
      - retina
      - thalamus
      - visual_cortex
      - decoder
      - inferotemporal_decoder
    weights:
      - ${recon_weight_retina}
      - ${recon_weight_thalamus}
      - ${recon_weight_cortex}
      - 1
      - 1
