# BrainOptimizer config. Each top level defines a particular optimizer. Circuits
# should appear in at most one optimizer.
recon:
  optimizer: # torch.optim Class and parameters
    _target_: torch.optim.Adam
    lr: 0.0003
  min_epoch: 0 # Epoch to start optimizer
  max_epoch: 100 # Epoch to stop optimizer
  objectives: # Weighted optimizer objectives as defined in retinal-rl
    - _target_: retinal_rl.models.objective.ReconstructionObjective
      weight: 1
    - _target_: retinal_rl.models.objective.L1Sparsity
      weight: 0.001
      target_responses:
        - retina
  target_circuits: # Circuit parameters to optimize with this optimizer.  We train the retina and the decoder exclusively to maximize reconstruction
    - retina
    - decoder
mixed:
  optimizer:
    _target_: torch.optim.Adam
    lr: 0.0003
  min_epoch: 0
  max_epoch: 100
  objectives:
    - _target_: retinal_rl.models.objective.ReconstructionObjective
      weight: 0.99
    - _target_: retinal_rl.classification.objective.ClassificationObjective
      weight: 0.01
  target_circuits: # The thalamus is somewhat sensitive to task objectives
    - thalamus
class:
  optimizer:
    _target_: torch.optim.Adam
    lr: 0.0003
  min_epoch: 0
  max_epoch: 100
  objectives:
    - _target_: retinal_rl.classification.objective.ClassificationObjective
      weight: 1
    - _target_: retinal_rl.classification.objective.PercentCorrect
      weight: 0
  target_circuits: # Visual cortex and downstream layers are driven by the task
    - visual_cortex
    - pfc
    - classifier
