name: Code Checking

on: 
  push:
    # paths:
    #   - '**/*.py'
  pull_request:
    branches:
      - main

jobs:
  init:
    uses: ./.github/workflows/get_singularity.yml
    with:
      singularity_image: oras://ghcr.io/berenslab/retinal-rl:singularity-image-latest
      sif_file: retinal-rl_singularity-image-latest.sif

  lint:
    needs: init
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Fetch all branches
      run: git fetch --all
    - name: Run Pylint
      run: |
        singularity exec ~/singularity_images/retinal-rl_singularity-image-latest.sif \
        pylint $(git diff --name-only origin/master...HEAD -- '*.py')
