name: Code Checking

on:
  pull_request:
    branches:
      - master
    paths:
      - '**/*.py'

env:
  singularity_image: oras://ghcr.io/berenslab/retinal-rl:singularity-image-latest
  sif_file: retinal-rl_singularity-image-latest.sif

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Fetch all branches
      run: git fetch --all

    - name: Setup Apptainer
      uses: eWaterCycle/setup-apptainer@v2
      with:
        apptainer-version: 1.3.0
    - name: Cache Singularity Image
      id: cache-singularity
      uses: actions/cache@v4
      with:
        path: ${{ env.sif_file }}
        key: ${{ runner.os }}-singularity-${{ hashFiles('~/resources/retinal-rl.def') }}
        restore-keys: |
          ${{ runner.os }}-singularity-${{ hashFiles('~/resources/retinal-rl.def') }}
          ${{ runner.os }}-singularity-
    - name: Pull Singularity container
      if: steps.cache-singularity.outputs.cache-hit != 'true'
      run: apptainer pull ${{ env.sif_file }} ${{ env.singularity_image }}

    - name: Run Pylint
      run: |
        apptainer exec ${{ env.sif_file }} \
        pylint $(git diff --name-only origin/master...HEAD -- '*.py')
