name: Code Checking

on: 
  push:
    paths:
      - '**/*.py'
  pull_request:
    branches:
      - main

env:
  singularity_image: oras://ghcr.io/berenslab/retinal-rl:singularity-image-latest
  sif_file: retinal-rl_singularity-image-latest.sif

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: eWaterCycle/setup-apptainer@v2
      with:
        apptainer-version: 1.3.0
    - uses: ./.github/workflows/setup.yml
      with:
        singularity_image: ${{ env.singularity_image }}

    - name: Run Pylint
      run: singularity exec ${{ env.sif_file }} pylint $(git diff --name-only origin/master HEAD -- '*.py')
