name: Code Checking

on: 
  push:
    paths:
      - '**/*.py'
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: eWaterCycle/setup-apptainer@v2
      with:
        apptainer-version: 1.3.0

    - name: Pulling Singularity container
      run: |
        singularity registry login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} oras://ghcr.io
        singularity pull oras://ghcr.io/berenslab/retinal-rl:singularity-image-latest

    - name: Run Pylint
      run: singularity exec retinal-rl_singularity-image-latest.sif pylint $(git diff --name-only origin/master HEAD -- '*.py')
