name: Code Checking

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  singularity_image: oras://ghcr.io/berenslab/retinal-rl:singularity-image
  sif_file: retinal-rl_singularity-image.sif

jobs:
  check-container-changed:
    name: Check if the def file changed
    uses: ./.github/workflows/check_def_changed.yml
  check:
    needs: check-container-changed
    if: needs.check-container-changed.outputs.file_changed == 'false'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Fetch all branches
      run: git fetch --all

    - name: Setup Apptainer
      uses: eWaterCycle/setup-apptainer@v2
      with:
        apptainer-version: 1.3.0

    - name: Cache Singularity Image
      id: cache-singularity
      uses: actions/cache@v4
      with:
        path: ${{ env.sif_file }}
        key: ${{ runner.os }}-singularity-${{ hashFiles('~/resources/retinal-rl.def') }}
        restore-keys: |
          ${{ runner.os }}-singularity-${{ hashFiles('~/resources/retinal-rl.def') }}

    - name: Run Linter / Code check
      run: bash tests/ci/lint.sh ${{ env.sif_file }}
