name: Code Checking

on: 
  push:
    # paths:
    #   - '**/*.py'
  pull_request:
    branches:
      - main

env:
  singularity_image: oras://ghcr.io/berenslab/retinal-rl:singularity-image-latest
  sif_file: retinal-rl_singularity-image-latest.sif

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/workflows/setup.yml
      with:
        singularity_image: ${{ env.singularity_image }}

  lint:
    needs: init
    runs-on: ubuntu-latest
    steps:
    - name: Run Pylint
      run: singularity exec ${{ env.sif_file }} pylint $(git diff --name-only origin/master HEAD -- '*.py')
