name: Scan Configs
on: 
  pull_request:
  workflow_dispatch:

env:
  singularity_image: oras://ghcr.io/berenslab/retinal-rl:singularity-image
  sif_file: retinal-rl_singularity-image.sif

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Apptainer
      uses: eWaterCycle/setup-apptainer@v2
      with:
        apptainer-version: 1.3.0
    - name: Cache Singularity Image
      id: cache-singularity
      uses: actions/cache@v4
      with:
        path: ${{ env.sif_file }}
        key: ${{ runner.os }}-singularity-${{ hashFiles('~/resources/retinal-rl.def') }}
        restore-keys: |
          ${{ runner.os }}-singularity-${{ hashFiles('~/resources/retinal-rl.def') }}

    - name: Prepare experiment files
      if: steps.cache-singularity.outputs.cache-hit == 'true'
      run: bash tests/ci/copy_configs.sh ${{ env.sif_file }}

    - name: Scan configs
      if: steps.cache-singularity.outputs.cache-hit == 'true'
      run: bash tests/ci/scan_configs.sh ${{ env.sif_file }}
