name: Scan Configs
on: [pull_request,workflow_dispatch]

jobs:
  init:
    uses: ./.github/workflows/setup.yml
    with:
      singularity_image: oras://ghcr.io/berenslab/retinal-rl:singularity-image-latest

  scan:
    needs: init
    runs-on: ubuntu-latest
    steps:
    - name: Scan classification config
      run: singularity exec retinal-rl_singularity-image-latest.sif python main.py -m +experiment=cifar10-class-recon command=scan system.device=cpu