name: Scan Configs
on: [pull_request,workflow_dispatch]
jobs:
  scan:
    uses: ./.github/workflows/singularity_pull.yml
    with:
      singularity_image: oras://ghcr.io/berenslab/retinal-rl:singularity-image-latest