name: Build Singularity Container

on: 
  push:
    branches-ignore:
      - master
    paths:
      - 'resources/retinal-rl.def'
  pull_request:
    branches:
      - master
    paths:
      - 'resources/retinal-rl.def'
  workflow_call:
    inputs:
      deploy:
        type: boolean
        required: false
        default: true
  workflow_dispatch:
    inputs:
      deploy:
        type: boolean
        required: false
        default: true

env:
  singularity_image: oras://ghcr.io/berenslab/retinal-rl:singularity-image
  sif_file: retinal-rl_singularity-image.sif

jobs:
  singularity-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: eWaterCycle/setup-apptainer@v2
      with:
        apptainer-version: 1.3.0
    
    - name: Evaluate whether build should be deployed
      id: setup
      run: |
        if [[ "${{ inputs.deploy }}" != "" ]]; then
          echo "deploy=${{ inputs.deploy }}" >> $GITHUB_OUTPUT
        else
          echo "deploy=false" >> $GITHUB_OUTPUT
        fi

    - name: Build Singularity container
      run: apptainer build ${{ env.sif_file }} resources/retinal-rl.def

    - name: Scan classification config / ensure minimal functionality
      run: |
        cp -r resources/config_templates/* config/
        apptainer exec ${{ env.sif_file }} python main.py -m +experiment=classification command=scan system.device=cpu

    - name: Deployment / Push to ghcr.io
      if: steps.setup.outputs.deploy == 'true'
      run: |
        apptainer registry login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} oras://ghcr.io
        apptainer push ${{ env.sif_file }} oras://ghcr.io/berenslab/retinal-rl:singularity-image
