name: Build Singularity Container

on: [push, pull_request]

jobs:
  singularity-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: eWaterCycle/setup-apptainer@v2
      with:
        apptainer-version: 1.3.0

    - name: Build Singularity container
      run: apptainer build retinal-rl.sif resources/retinal-rl.def