name: Pylint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: eWaterCycle/setup-apptainer@v2
      with:
        apptainer-version: 1.3.0

    - name: Pulling Singularity container
      run: singularity pull oras://ghcr.io/berenslab/retinal-rl:singularity-latest

    - name: Run Pylint
      run: singularity exec retinal-rl_singularity-image-latest.sif pylint $(git diff --name-only origin/master origin/feat-ci-pipeline -- '*.py')
