name: Pull Singularity container & Setup Repository

on:
  workflow_call:
    inputs:
      singularity_image:
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.3.0
      - name: Login to ghcr
        run: singularity registry login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} oras://ghcr.io
      - name: Pull Image
        run: singularity pull ${{ inputs.singularity_image }}
      - name: Copy Configs
        run: cp -r resources/config_templates/* config/