name: Reusable Pull and Scan

on:
  workflow_call:
    inputs:
      singularity_image:
        required: true
        type: string

jobs:
  reusable_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.3.0
      - name: Login to ghcr
        run: singularity registry login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} oras://ghcr.io
      - name: Pull Image
        run: singularity pull ${{ inputs.singularity_image }}
      - name: Scan classification config
        run: |
          cp -r resources/config_templates/* config/
          IMAGE_NAME=$(basename ${{ inputs.singularity_image }})
          SIF_FILE="${IMAGE_NAME/:/_}.sif"
          singularity exec $SIF_FILE python main.py -m +experiment=cifar10-class-recon command=scan system.device=cpu