name: Update Master Cache

on: 
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'resources/retinal-rl.def'

env:
  singularity_image: oras://ghcr.io/berenslab/retinal-rl:singularity-image-latest
  sif_file: retinal-rl_singularity-image-latest.sif
  
jobs:
  container-build:
    uses: ./.github/workflows/container_build.yml
  update-cache:
    needs: container-build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Apptainer
      uses: eWaterCycle/setup-apptainer@v2
      with:
        apptainer-version: 1.3.0
    - name: Cache Singularity Image
      id: cache-singularity
      uses: actions/cache@v3
      with:
        path: ${{ env.sif_file }}
        key: ${{ runner.os }}-singularity-${{ hashFiles('~/resources/retinal-rl.def') }}
        restore-keys: |
          ${{ runner.os }}-singularity-${{ hashFiles('~/resources/retinal-rl.def') }}
          ${{ runner.os }}-singularity-
    - name: Pull Singularity container
      if: steps.cache-singularity.outputs.cache-hit != 'true'
      run: |
        singularity registry login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} oras://ghcr.io
        singularity pull ${{ env.sif_file }} ${{ env.singularity_image }}
